### ISSUE TITLE
Criar design pro frontend

### ISSUE THREAD

**Issue by eng-ufba** [eng-ufba/chatgpt-poli#1]
## Informações:
O design do frontend já foi iniciado, mas precisa ser finalizado.
Link: https://www.figma.com/file/eacK3cBXavwFO7C1W5IOW4/Untitled?type=design&node-id=0-1&mode=design

## Todo
- [x] Página do primeiro acesso
- [x] Design próximo do site da poli
- [x] Homepage
- [x] Página de Termos de uso
- [x] Página de Política de Privacidade
