### ISSUE TITLE
Frontend: todas features

### ISSUE THREAD

**Issue by GeraldHamiltonWicks** [eng-ufba/chatgpt-poli#5]
## Todo
- [x] Sidebar funcional -> expandir e encolher
- [x] Responsividade para o mobile
- [x] Aparecer scrollbar quando carrega muitas mensagens
- [x] Mostrar ícone X quando a sidebar abre
- [x] Esconder ícone hamburguer no sidebar quando a tela é de desktop
- [x] Cachear as stores
- [x] Modal inicial perguntando do curso
- [x] Página de termos e serviços
- [x] Página de política de privacidade
- [x] Botão mudar de curso (no sidebar)
- [x] Modal de deletar
- [x] Editar o títudo do chat
- [x] Aparecer snackbar após clicar no copy button
- [x] Loading após as perguntas
- [x] Aparecer scrollbar quando tem muitos chats na sidebar
- [x] Não mostrar scrollbar quando n tem perguntas dentro do chat content
- [ ] Mensagem de error se ñ for possível carregar
- [ ] Botão para ir até o final da scrollbar
- [ ] Dropdown fechar quando clica fora
